### ISSUE TITLE
Error during importing into Android studio 1.0

### ISSUE THREAD

**Issue by wangbourne** [commonsguy/cwac-layouts#3]
Trying to import into Android Studio 1.0, I got the following error message:

Error:SDK location not found. Define location with sdk.dir in the local.properties file or with an ANDROID_HOME environment variable.

**Comment by commonsguy** [comment]
There's nothing in the project that specifies the SDK location, simply because it can be wherever you put it. Moreover, a new Android Studio installation knows usually knows where the SDK is, because it is the one that sets up the SDK.

Follow the instructions in the message, or try creating another Android Studio project first (as it should remember your SDK configuration from before).

Regardless, I do not see how this issue is tied to this particular project.
